# nginx-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        
        location / {
          root /var/www/html;
          try_files $uri $uri/ /index.php$is_args$args;
        }
        
        location ~ consumer\.php$ {
          root /var/www/html;
          fastcgi_pass consumer-service:9000;
          fastcgi_index /var/www/html/index.php;
          fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
          include fastcgi_params;
        }
        location ~ \.php$ {
          root /var/www/html;
          fastcgi_pass producer-service:9000;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
          include fastcgi_params;
        }
      }
    }